# parameters for the feature interpolation pipeline
# that trains a spatial interpolation model on the extracted features
target: "wave_height"
model: lightgbm.LGBMRegressor
num_jobs: 25

data_loading:
  start: "2011-01-01"
  end: "2022-01-01"
  buoy_dataset: "data/04_feature/buoy_stdmet_data/*.parquet"
  buoy_geo_dataset: data/03_processed/buoy_locations_geo/buoy_locations.parquet


feature_extraction:
  make_features_params:
    k_nearest: 4
    feature_vars: ["wave_height", "wind_speed"]
    add_directions: True
    ground_truth: wave_height

  preprocess_params:
    buoy_data_funcs:
      - rename_axis: [["location_id","time"]]
      - dropna: {"how":"any", "subset":["wave_height"]}
    buoy_geo_funcs:
      - rename_axis: [["year","location_id"]]
      - dropna: {"how":"any"}
  
  postprocess_params:
    - dropna : {"how":"any"} # drop rows with missing values
    - sort_index: {} # sort the index

pretrain_funcs:
    - drop: {"columns":["x","y"]}
    - filter:   # filter out irrelevant identification columns
        regex : "^((?!location_\\d$).)*$"
    - dropna : {"how":"any"} # drop rows with missing values
    - sort_index: {} # sort the index
    - sort_index: {"axis": 1} # sort the columns by names


split_strategy:
  method: split_slice
  params:
    test: ["41001"]

# validation_strategy:
#   strategy: random
#   params:
#     random_state: 42
#     n_splits: 3
#     eval_locations: 2
#     test_size: 0.2
#     priorize_test_set: False
#     split_on_unique: True
  
model_evaluation:
  log_mlflow: True
  log_shap: True
  shap_by_location: True

model_params:
  objective: 'regression'
  # best params:
  learning_rate: 0.075
  n_estimators: 650
  max_depth: 5
  num_leaves: 15
  subsample_freq: 5
  subsample: 0.75
  colsample_bytree: 0.75

gridsearch_params:
  n_jobs: 1
  verbose: 3
  scoring: "rmse"
  param_grid:
    max_depth: [3, 10, 15]
    num_leaves: [7, 9, 15, 20]
    colsample_bytree: [0.5, 0.75, 1.0]
    subsample: [0.5, 0.75, 1.0]