target: wave_height
n_jobs: 20
eval_frac: 0.35

krige_params:
    method: ordinary
    variogram_model: linear
    weight: False
    n_closest_points: 4
  

data_loading:
  start: "2011-01-01"
  end: "2022-01-01"
  buoy_dataset: "data/04_feature/buoy_stdmet_data/*.parquet"
  buoy_geo_dataset: data/03_processed/buoy_locations_geo/buoy_locations.parquet

map_params:
  folium_map:
    zoom_start: 5
  # marker: life-buoy
  # prefix: fa

grid:
  boundaries: [-98.251934,12.282308,-45,35.55]
  resolution: 0.1